"use client";

import { use } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { MarkdownContent } from "@/components/common/MarkdownContent";
import { Badge } from "@/components/ui/badge";
import { useLibraryNote } from "@/hooks/app";

export default function NoteDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const { data: note, isLoading, error } = useLibraryNote(id);

  return (
    <div className="min-h-full px-4 py-8">
      <div className="mx-auto max-w-3xl">
        <Link
          href="/app/notes"
          className="inline-block mb-6 text-[10px] font-mono uppercase tracking-widest text-muted-foreground/50 hover:text-primary transition-colors"
        >
          ← All Notes
        </Link>

        {isLoading && (
          <div className="space-y-3">
            {[...Array(4)].map((_, i) => (
              <div
                key={i}
                className="h-14 animate-pulse bg-card/40 border border-border/30"
              />
            ))}
          </div>
        )}

        {!isLoading && error && (
          <div className="border border-destructive/40 bg-destructive/5 px-4 py-3 text-sm font-mono text-destructive">
            Failed to load note.
          </div>
        )}

        {note && (
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <h1 className="text-2xl font-black tracking-tighter">
              {note.title}
            </h1>
            <div className="mt-2 flex items-center gap-2 flex-wrap">
              {note.generatedByZ && (
                <Badge
                  variant="outline"
                  className="text-[9px] font-mono h-4 px-1.5"
                >
                  Generated by Z
                </Badge>
              )}
              {note.courseTitle && (
                <Badge
                  variant="outline"
                  className="text-[9px] font-mono h-4 px-1.5"
                >
                  {note.courseTitle}
                </Badge>
              )}
              {note.sessionName && (
                <Badge
                  variant="outline"
                  className="text-[9px] font-mono h-4 px-1.5"
                >
                  {note.sessionName}
                </Badge>
              )}
            </div>
            <div className="mt-4 h-px w-10 bg-primary/40" />

            <div className="mt-6 border border-border/40 bg-card/20 p-4">
              <div className="prose prose-sm prose-invert max-w-none text-[12px] font-mono leading-relaxed">
                <MarkdownContent>{note.content}</MarkdownContent>
              </div>
            </div>

            <div className="mt-4">
              <Link
                href={`/app/${note.sessionId}`}
                className="text-[10px] font-mono uppercase tracking-widest text-primary hover:underline"
              >
                Open source session →
              </Link>
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
}
